### ISSUE TITLE
r2c-1000 corpus only contains 882 repos

### ISSUE THREAD

**Issue by dlukeomalley** [returntocorp/cli#10]
The `r2c-corpus` only contains 882 repos, but says it contains 1000 in it's description and the getr2c tutorial.

![image](https://user-images.githubusercontent.com/605906/55753685-ccdbcc00-59ff-11e9-93cb-4ed0267f1a20.png)

Should it have 1000 repos?

**Comment by dlukeomalley** [comment]
CC @ievans who started work to fix this.

**Comment by ievans** [comment]
@dlukeomalley this is fixed and @DrewDennison has uploaded the new corpus

**Comment by dlukeomalley** [comment]
Thank you for the follow-up! Closing out 🎉
