### ISSUE TITLE
Large `InfraError` rate, unclear next steps for user to debug or fix

### ISSUE THREAD

**Issue by dlukeomalley** [returntocorp/cli#12]
A user is developing an analyzer and running it on the `r2c-100` corpus. They're getting a 58% error rate due to `InfraError` with no log output or clear next steps.

Questions:

1) What is happening behind the scenes, and are all 58/100 errors the same?
2) In cases where there is a 58% error rate for a non-user related bug, what kind of alerting is there and how should the user progress?

![image](https://user-images.githubusercontent.com/605906/55756561-b38a4e00-5a06-11e9-9c8c-e0e600c3951b.png)

**Comment by dlukeomalley** [comment]
Ran into this again today where we showed an InfraError with the following log associated with it:

```
Counting lines in file ./index.js
test or bin or docs file found : ./tests.js
Skipping file
```

I believe the analyzer just isn't writing an `output.json` file. Digging into the network logs, I found the following:

```
errorMessage: "the JSON object must be str, bytes or bytearray, not NoneType↵  File "/r2c/batch/lib/message_processing_unit.py", line 56, in poll↵    process_output = self.process_message(message)↵  File "/r2c/batch/analysis_ingester/analysis_ingester.py", line 264, in process_message↵    self.process_message_new(message)↵  File "/r2c/batch/analysis_ingester/analysis_ingester.py", line 356, in process_message_new↵    raise e↵  File "/r2c/batch/analysis_ingester/analysis_ingester.py", line 353, in process_message_new↵    json_data = json.loads(json_string)↵  File "/usr/local/lib/python3.7/json/__init__.py", line 341, in loads↵    raise TypeError(f'the JSON object must be str, bytes or bytearray, '↵"
errorType: "InfraError"
status: "ingest_fail"
```

Is it possible to safely tell the author that this is an issue with analyzer, not with infrastructure?

**Comment by ulziibay** [comment]
@dlukeomalley: We surface `AnalyzerNonZeroExit` to indicate that the users docker is failing correct? Is this asking for additional breakdown by sub-error type? 

> what kind of alerting is there and how should the user progress?

Not sure if alerting should be builtin to the product. I think a good place for the is the notification nub on the platform UI.

**Comment by ulziibay** [comment]
I think the error types are broken down on wildwest and we surface the logs for those in the UI when we can.
```
 AnalyzerNonZeroExitError |   194
 ChunkedEncodingError     |    21
 InvalidAnalyzerOutput    |    36
 TypeError                |     4
 UnicodeEncodeError       |     3
```
As for alerting, @DrewDennison, do you know if/how we can setup alerting on DB row count like this via Datadog or something?

**Comment by dlukeomalley** [comment]
<quick_thoughts>

The issue's I'm facing is that `InfraError` isn't always an issue with the infrastructure per say, but analyzer output or analyzer errors causing infra failures (in the case of the missing `output.json` file, issues with people's docker, network timeouts, etc.).

From a UI perspective, I think what I'm missing is the ability to see the infra error (I often go to Chrome debugger network tab to get the error message out of the server response) or better classification of errors beyond `InfraError`, so maybe something like `InfraError.DockerFailure`. I've observed that once people get `InfraError` they're stuck unless they come talk to us.

When I'm thinking about alerting, I'm thinking about notifying r2c staff when a job has a high `InfraError` rate just because it means something is either off about prod or there is a misunderstanding about how to write an analyzer.

Up for chatting today about this in person?

</quick_thoughts>

**Comment by arashd** [comment]
Moving this over to the backend repo https://github.com/returntocorp/echelon-backend/issues/3330
