### ISSUE TITLE
Add ability to filter tasks on jobs page

### ISSUE THREAD

**Issue by dlukeomalley** [returntocorp/cli#13]
From a user:

> A feature that I'm missing is some way to filter failing/succeeding cases in the jobs view.

Follow-up questions asked:

> Great idea. Couple questions to make sure I fully understand the ask:
> 
> 1. What does filtering tasks enable for you?
> 2. In what ways does clicking on Errors not work for you?
> 3. What kind of filtering do you have in mind? Text search? Sorting?
> 4. Is there any other software that you use that has filtering of the kind you have in mind?

Does anyone else have this same FR and have answers for the above questions?

**Comment by tnarla** [comment]
Added filtering: https://github.com/returntocorp/echelon-backend/pull/3110. Closing for now, can create new issue for more specific filtering ask
