### ISSUE TITLE
Unclear sort order for tasks on jobs page

### ISSUE THREAD

**Issue by dlukeomalley** [returntocorp/cli#16]
Tasks aren't in any discernible order on the jobs page, making it hard to paginate and know what to expect on pg 2 vs. pg 3. Could we sort alphabetically by default to lend more meaning to pagination?

![image](https://user-images.githubusercontent.com/605906/55817228-e2590080-5aa8-11e9-9cb5-77799b1e7b2d.png)

**Comment by dlukeomalley** [comment]
Ran into this issue again, but this time the list jumped order while the job was running. I believe @ievans has seen this behavior before too.

![jumping](https://user-images.githubusercontent.com/605906/56379576-debe2b80-61c4-11e9-9731-8be86c76dc6e.gif)

**Comment by dlukeomalley** [comment]
> Results table should be in a stable order by default, probably by showing jobs that have not started yet.
> 
> Example of why this is a problem:
> 
> Look at a job, go to page 5
> Open the log and start reading it
> Forget what repo you were on
> Go back to the jobs page and you have no clue where that repo went

**Comment by tnarla** [comment]
Fixed with https://github.com/returntocorp/echelon-backend/pull/3110
