### ISSUE TITLE
Make it easier to locally debug a failing task on the platform

### ISSUE THREAD

**Issue by dlukeomalley** [returntocorp/cli#19]
If a task fails and I currently want to debug it locally I have to git clone the relevant repo, checkout the right commit (lots of copy-pasta from the web UI), navigate to my analyzers directory, and call `r2c run`. Instead, I'd love if each task gave me the ability to copy a command to run locally that does this stuff for me. It would be enough to give me a command like the following to run:

```
r2c run https://github.com/facebook/jest 2fc468
```

Currently the UI just shows me:

![image](https://user-images.githubusercontent.com/605906/55920734-b88a0180-5bae-11e9-800d-842545fe3f04.png)

I think this involves two parts:

1) Add a feature to the CLI that supports passing in git and other urls rather than a code directory
2) Update the UI to generate the string that uses #1

**Comment by ulziibay** [comment]
I heard this from @aryx as well. I will working on this feature to the next release of CLI

**Comment by ievans** [comment]
Disagree we should support arbitrary non-local inputs for r2c run. Let's put a dropdown in the jobs table with a bash-one-liner to git clone checkout and r2c run to reproduce issues

**Comment by ulziibay** [comment]
@dlukeomalley @ievans you should deconflict here. I personally think commands like `r2c run https://github.com/facebook/jest 2fc468` is going to used a lot and will be immediately useful!

**Comment by ulziibay** [comment]
Chatted with @dlukeomalley and @ievans! Adding complexity `r2c run` command of inferring, validating, and cloning non-local input: we will just add a copy-paste lines in the UI that does `git clone` and `r2c run`. CLI code does not have to change.

**Comment by ievans** [comment]
thanks to @dlukomalley and @brendon for changing my mind here!

**Comment by tnarla** [comment]
fixed with https://github.com/returntocorp/echelon-backend/pull/3263
