### ISSUE TITLE
r2c run: /analysis is empty on ubuntu 18.04

### ISSUE THREAD

**Issue by cjtenny** [returntocorp/cli#21]
## What happened?

Going through tutorial with left-pad, error changing directory to source-code.

find and ls -a show /analysis is empty.

From the user, author fields redacted:

> I was trying to follow through the “Getting Started” guide on a Google Cloud instance running Ubuntu 18.04 LTS, and I keep running into this error:
> 
> 🔎 Running analysis on `/home/<user>/test-repos/left-pad`
> 
> /analyzer/analyze.sh: line 6: cd: /analysis/inputs/public/source-code: No such file or directory
> 
> ❌ There was an exception: Docker container finished with non-zero exit code: 1.
> 
> Container log /analyzer/analyze.sh: line 6: cd: /analysis/inputs/public/source-code: No such file or directory
> 
>  Command run:
> 
> $  sudo /home/<user>/.local/bin/r2c run ~/test-repos/left-pad
> 

-------------- analyze.sh ---------------
```
#!/bin/bash

set -e
CODE_DIR="/analysis/inputs/public/source-code"

cd ${CODE_DIR}

find . -name '*.js' | xargs python3 /analyzer/whitespace.py
```
-------------- analyzer.json -------------
```
{
    "analyzer_name": "ecs260-N/minifinder",
    "version": "0.0.1",
    "spec_version": "1.2.0",
    "dependencies": {
        "public/source-code": "*"
    },
    "type": "commit",
    "output": {
        "type": "json"
    },
    "deterministic": true
}
```

**Comment by arashd** [comment]
@deifactor might have insight into this since she fixed our mounting/permissions issues on ubuntu recently.

**Comment by cjtenny** [comment]
Detailed repro steps:

Machine Type:
n1-standard-1 (1 vCPU, 3.75 GB memory) with 10GB persistent storage running Ubuntu 18.04 LTS.

```
sudo snap install docker
sudo apt update
sudo apt install python3-pip
sudo pip3 install r2c-cli
PATH=”$PATH: /home/<user>/.local/bin/”
```
Then run tutorial verbatim

**Comment by cjtenny** [comment]
Issue turns out to come from `snap` distribution of docker. Reinstall with Docker CE official installation steps fixes. We should investigate, but med-pri.

**Comment by imanchatterjee** [comment]
I am facing the same issue

**Comment by deifactor** [comment]
I can take a look at this today. It's weird that there's a difference.

**Comment by deifactor** [comment]
Per [the documentation on docker snap](https://git.launchpad.net/~docker/+git/snap/tree/README.md), it looks like the snap-ified version of Docker requires all the files that docker reads be under `$HOME`. We could maybe make this work by detecting whether Docker is installed via a snap and then using $HOME/.r2c/tmp if it is.

**Comment by ulziibay** [comment]
are we considering this resolved? what are the action items here?

**Comment by deifactor** [comment]
I opened returntocorp/docs#27 to document that this doesn't work. I don't think this is worth the effort on our end, but if we wind up really wanting to support snap docker then we can reopen.

**Comment by imanchatterjee** [comment]
Hi,
Docker ce is not supported on windows 7 machine.So we had to use an older
version docker.io which is supported by our virtual box.This particular
error happens with docker.io.For now I have been able to install docker Ce
on my google cloud vm and that is where I am running the project.But it
would be really helpful if the issue on your end could be solved to
accomodate docker.io(for those that have Windows 7 on their PCs) users.
Thanks

**Comment by deifactor** [comment]
I'm a bit confused. It sounds like you're running VirtualBox on a physical Windows 7 machine, is that correct? If so, what operating system is the virtual machine running, and how did you install Docker in it?

**Comment by imanchatterjee** [comment]
I was using Docker Toolbox
https://docs.docker.com/toolbox/toolbox_install_windows/
The image being used was a bionic image(latest)

**Comment by deifactor** [comment]
Ah, sorry, I misunderstood. We don't currently support installing Docker directly on Windows, so you'll want to make a Bionic image (or similar) and install Docker inside the image via [these instructions](https://docs.docker.com/install/linux/docker-ce/ubuntu/).

**Comment by imanchatterjee** [comment]
Yes.I followed the instructions and got my docker working in the virtual
box. .However ,the analysis folder that gets created remains empty and
docker was not able to find it in runtime.I believe I was running the
entire process inside a docker container(docker within docker) and I
installed r2c inside this container.
For today's homework,I have been able to use r2c on google cloud(which
supports docker ce) and get results
