### ISSUE TITLE
Able to upload my own input sets

### ISSUE THREAD

**Issue by dlukeomalley** [returntocorp/cli#24]
More and more people want to analyze custom corpora and are asking us to add them. This is a general tracking ticket for this feature.

How would you like to create or add a custom corpus? Through the CLI or web UI? Are you comfortable creating a text file, or do you expect something graphical?

**Comment by ulziibay** [comment]
Tracked at https://returntocorp.quip.com/OnHyAMvnurJg/Input-Set-Creation

**Comment by ulziibay** [comment]
Per june doc, i believe @DrewDennison  and @brendongo  handling this

**Comment by ulziibay** [comment]
@tnarla would be involved i believe

**Comment by arashd** [comment]
this is solved with `r2c upload-inputset`
