### ISSUE TITLE
Support for windows

### ISSUE THREAD

**Issue by tjchambers32** [returntocorp/cli#3]
Do you plan on supporting Windows in the future? Your documentation doesn't mention windows anywhere (that I can see), but I just tried to run r2c and I'm running into some Unix specific methods that won't work on Windows.

**Comment by dlukeomalley** [comment]
@tjchambers32 I'm sorry to hear about the issues you're running into. What version of Windows are you running? Is there a chance you're able to run an Ubuntu (or similar) VM to use the CLI within?

**Comment by tjchambers32** [comment]
Windows 10. I'm trying it right now with Windows Linux Subsystem. Will report back if I'm able to succeed.

**Comment by dlukeomalley** [comment]
Awesome, I think that should work. Unfortunately we don't have anyone running Windows here and can't confirm ourselves, but happy to make some changes to support you if you run into problems.

**Comment by tjchambers32** [comment]
I've run into some problems, though those are summed up in another issue. It may be related to me not having a login yet.

**Comment by dlukeomalley** [comment]
I think so too. I'm going to close this out for now and will push an update to our docs that touches on our "officially supported" operating systems.

https://github.com/returntocorp/docs/pull/22
