### ISSUE TITLE
Hide old versions of analyzers in the frontend

### ISSUE THREAD

**Issue by deifactor** [returntocorp/cli#31]
In general, only the latest few versions of an analyzer are going to be worth anything, and it's confusing having a bunch of old versions of stuff hanging around.

**Comment by arashd** [comment]
One feature request we've had before and @tnarla is working on is to group all versions of an analyzer. makes things a lot nicer. I also liked the old dropdown with search we had in /home

**Comment by ulziibay** [comment]
This is added to UI already right @deifactor? Please close if not
