### ISSUE TITLE
public analyzers without login fails

### ISSUE THREAD

**Issue by DrewDennison** [returntocorp/cli#33]
## What happened?

should be able to pull public analyzers without login
## What did you expect to happen?

pulling public analyzers without login
## To reproduce
1. Run `r2c logout`
2. Run `r2s run ...`
3. See 
![image](https://user-images.githubusercontent.com/1011067/57089824-2d39f280-6cba-11e9-811f-4c0dd1297d0c.png)

4. Expect to see output

**Comment by DrewDennison** [comment]
cat ~/.r2c/credentials.json
{}

**Comment by ulziibay** [comment]
@DrewDennison is `example` analyzer a new analyzer? If so, I am able to run it without logging in. I think this error could be due to docker hub issues (https://status.docker.com/). Can you elaborate on which analyzer?

**Comment by ulziibay** [comment]
Found the problem to be an incomplete special casing on our end.  ETA for fix will be tomorrow!
