### ISSUE TITLE
r2c push does not check login state

### ISSUE THREAD

**Issue by ievans** [returntocorp/cli#37]
rm -rf ~/.r2c
> r2c push
✘ Attempting to push to organization: `None`. However, the org specified as the prefix of the analyzer name in `analyzer.json` does not match it. Replace `dev` with `None` and try again.Please ask for help from R2C support

**Comment by ulziibay** [comment]
With 0018 it would say the following
```
You are not logged in. Please run `r2c login` to be able to push your analyzer        
```
