### ISSUE TITLE
Remove all references to MAP and Massive in UI and CLI

### ISSUE THREAD

**Issue by dlukeomalley** [returntocorp/cli#42]
The UI, CLI, and possibly backend error messages have outdated references to MAP/Massive. With the move to app.r2c.dev, let's vanquish them!

Example is when a job is submitted, it reads `Submitting to Massive`

**Comment by ulziibay** [comment]
I can clean this up

**Comment by DrewDennison** [comment]
can you link the PR @ulziibay ?

**Comment by DrewDennison** [comment]
this is marked as done on the spreadsheet

**Comment by ulziibay** [comment]
https://github.com/returntocorp/echelon-backend/pull/3213/files
