### ISSUE TITLE
Header and content styling on /analyzer and /inputs mismatches

### ISSUE THREAD

**Issue by dlukeomalley** [returntocorp/cli#49]
![image](https://user-images.githubusercontent.com/605906/58389018-282b4300-7fdb-11e9-9198-2804cb6283cb.png)

![image](https://user-images.githubusercontent.com/605906/58389024-2ceff700-7fdb-11e9-8e2a-01111381ee21.png)

**Comment by tnarla** [comment]
Talked with @dan5382, the frontend will follow the styling in figma and should be fixed now!
