### ISSUE TITLE
r2c push doesn't make sure image has been built

### ISSUE THREAD

**Issue by ievans** [returntocorp/cli#54]
r2c push should ensure that the image has been built before it's ready to be pushed!

**Comment by ulziibay** [comment]
the docker build and docker push commands are executed sequentially. How did you arrive at this error?

**Comment by ulziibay** [comment]
`r2c push` is aborted if image is not built per https://github.com/returntocorp/echelon-backend/blob/develop/r2c/cli/r2c/cli/commands/push.py#L152. This is a no-op. Closing!
