### ISSUE TITLE
r2c push should let me squash images before pushing

### ISSUE THREAD

**Issue by ievans** [returntocorp/cli#55]
I'm deleting some intermediary artifacts--it would be great to have an option to squash the container before we push it.

**Comment by ulziibay** [comment]
Why? Doesn't squashign the incrementality of the artifacts goes against the `docker push` mental model? Does squashing save time or resources? 
i like the incremental push because it can pick up where it left off.

**Comment by ievans** [comment]
Agreed in the general case -- but not if the artifact size is >> the final image size.

**Comment by ulziibay** [comment]
`r2c push --squash` sounds good to me!

**Comment by ulziibay** [comment]
`docker build --squash` is only supported on a Docker daemon with experimental features enabled! So this command will apply to those subsection of users who has that enabled

**Comment by ievans** [comment]
@ulziibay would it be possible to have this on `r2c --build` as well?
