### ISSUE TITLE
What version of python is required?

### ISSUE THREAD

**Issue by dlukeomalley** [returntocorp/cli#67]
Sister ticket for https://github.com/returntocorp/docs/issues/35. The CLI should check that it's python and other env requirements are met.

**Comment by ulziibay** [comment]
We check 3.6 above in the CLI and error our accordingly in https://github.com/returntocorp/echelon-backend/blob/develop/r2c/cli/r2c/cli/commands/cli.py#L70. I believe doc should be fixed to say 3.6 or above so that the installation does not fail!

**Comment by ulziibay** [comment]
See https://github.com/returntocorp/docs/pull/37 for updating the docs!
