### ISSUE TITLE
r2c command not found when trying to run r2c-cli for the first time

### ISSUE THREAD

**Issue by pabloest** [returntocorp/cli#75]
## What happened?

I tried to install and run `r2c-cli` following the [installation instructions](https://docs.r2c.dev/en/latest/intro/installation.html) in docs. In step 1.1.2, after successfully installing `r2c-cli`using pip3, I attempted to perform the final instruction in the step, which is to verify the installation. My terminal returned an error: `-bash: r2c: command not found` 

## What did you expect to happen?

I expected to see the same output shown in the docs page.

## To reproduce

I am not sure. This might be related to my environment. I assumed the error was related to my machine not finding the `r2c` program in its path or similar? When I opened a new terminal tab, I was able to successfully run `r2c --help` and see the same output as shown on the docs page.

## Specs

- OS: macOS Mojave 10.14.5 (18F132)
- Python Version: Python 3.7.4
- Docker Version: Version 2.0.0.3 (31259)

**Comment by ulziibay** [comment]
@dlukeomalley do you remember if we added PATH related troubleshooting to our doc? I think we have seen this issue before! Like,this is because we need `/usr/local/bin` in the path variable. The fix would be `PATH=$PATH:/usr/local/bin`

**Comment by pabloest** [comment]
Today I tried to run `r2c init` and ran into this same issue again. Here’s my `$PATH`: `/Users/pabloestrada/bin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/opt/sphinx-doc/bin`

**Comment by ulziibay** [comment]
This is addressed by making sure the path reported by `pip3 info r2c-cli` is in the $PATH variable!

**Comment by pabloest** [comment]
Thanks for your help, @ulziibay !
