### ISSUE TITLE
r2c run failed with "Connection aborted" error

### ISSUE THREAD

**Issue by dlukeomalley** [returntocorp/cli#8]
## What happened?

From a user:

> I was following the R2C tutorial but got stuck at '1.4. Running Analysis Locally' after running into the following error message:

```
Resolving dependencies
There was an exception: ('Connection aborted.', PermissionError(13, 'Permission denied')))
Please file a big report at ...
```

## Specs

- OS: Ubuntu (unknown version)

**Comment by dlukeomalley** [comment]
From @cjtenny

> This is probably because your Docker daemon isn't running! If you try `docker run hello-world`, you may see the same message. If starting or restarting your Docker daemon doesn't work, please post or send me the information in ~/.r2c/_logs/r2c-debug.log

**Comment by dlukeomalley** [comment]
Issue hit by another user. Believe it was docker daemon related again.

**Comment by DrewDennison** [comment]
We run docker info which should be catching this issue. Let’s try to repo

**Comment by DrewDennison** [comment]
At a minimum we should catch this error and throw a cli error with details about who to check docker is accepting connections

**Comment by ulziibay** [comment]
@DrewDennison @dlukeomalley can you get the user's `~/.r2c/_logs/r2c-debug.log`. Without that, determining the rootcause and repro-ing is hard to do!

**Comment by ulziibay** [comment]
cc: @arashd  as well

**Comment by ulziibay** [comment]
Seems like https://github.com/docker/docker-py/issues/2158 is similar to what the user ran into!
